version: "3"

services:
  eyesim:
    image: eyesim1.5.2:alpha-0.8
    container_name: eyesim
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .config:/home/eyesim/.config/   
    environment:
      - DISPLAY
    command: eyesim